# ETH Balance Watcher Configuration

# Ethereum RPC URL (can also be set via ETH_RPC_URL environment variable)
ethereum_rpc: "https://eth-mainnet.g.alchemy.com/v2/your-api-key"

# How often to check balances (can also be set via CHECK_INTERVAL environment variable)
check_interval: "60s"

# Port for metrics endpoint (can also be set via METRICS_PORT environment variable)
metrics_port: 9090

# Path to wallets file (can also be set via WALLETS_FILE environment variable)
wallets_file: "wallets.txt"